## ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"

## export HOMEBREW_CASK_OPTS="--appdir=/Applications"
## sudo -E bash
## brew bundle

## Homebrew
update
upgrade

brew tap phinze/homebrew-cask
install brew-cask
install bash zsh git tig tree wget rsync emacs curl tmux openssl ricty nkf

## Homebrew-cask
brew cask install google-chrome
brew cask install google-japanese-ime
brew cask install google-drive
brew cask install dropbox
brew cask install evernote
brew cask install skitch
brew cask install onepassword
brew cask install appcleaner
brew cask install the-unarchiver
brew cask install sophos-anti-virus-home-edition
brew cask install vlc
brew cask install xquartz

## Developer
brew cask install iterm2
brew cask install virtualbox
brew cask install vagrant
brew cask install heroku-toolbelt
brew cask install kobito
brew cask install licecap
brew cask install dash
brew cask install slack
brew cask install hoster
brew cask install github
brew cask install forklift

## AppStore
# line
# twitter

## download
# alfred2
# garmin-web-updater
# mame-osx
# pixelmator
