(source gnu)
(source marmalade)
(source melpa)

;; Setup
(depends-on "init-loader")

;; Auto-complete
(depends-on "auto-complete")
(depends-on "fuzzy")
(depends-on "popup")

;; Migemo
(depends-on "migemo")

;; Helm
(depends-on "helm")

;; Markdown
(depends-on "markdown-mode")

;; Ruby
(depends-on "ruby-mode")
(depends-on "ruby-end")
(depends-on "ruby-block")
(depends-on "robe")